### ISSUE TITLE
[Help] gradients are broken on Haiku

### ISSUE THREAD

**Issue by diversys** [memononen/nanosvg#177]
Hi, could you please check what could be a problem with gradients https://review.haiku-os.org/c/haiku/+/2661
Thanks.

**Comment by memononen** [comment]
Can you please provide an example of a gradient that does not work?

**Comment by diversys** [comment]
@PulkoMandy do you have one?

**Comment by pulkomandy** [comment]
The problem is not on nanosvg side for this, but in my lack of understanding of how to convert the nanosvg gradient transform to what our own code expects. And more specifically, in understanding what our code is expecting, once I understand that I can probably figure out how to convert the matrix (if possible) or modify the parser to output the info I need.

**Comment by memononen** [comment]
This discussion should be useful to you: https://github.com/memononen/nanosvg/issues/26

**Comment by pulkomandy** [comment]
Fixed my problems which were indeed not in nanosvg code. Issue can be closed :)

**Comment by diversys** [comment]
Cool! :)
